Use dedicated methods for registered claims and DateTimeImmutable timestamps
rediris-es/simplesamlphp-module-oidc pull request #67
Opened 2021-03-19 01:55 UTC by mdusher

This is just to fix the deprecation warnings being raised by Lobucci\JWT.

**Backtraces for the warnings:**
```
Mar 18 23:55:21 simplesamlphp ERROR [f8fecb1662] SimpleSAML\Error\Exception: Error 16384 - Using integers for registered date claims is deprecated, please use DateTimeImmutable objects instead. at /var/simplesamlphp/vendor/lcobucci/jwt/src/Builder.php:169
Mar 18 23:55:21 simplesamlphp ERROR [f8fecb1662] Backtrace:
Mar 18 23:55:21 simplesamlphp ERROR [f8fecb1662] 12 /var/simplesamlphp/www/_include.php:48 (SimpleSAML_error_handler)
Mar 18 23:55:21 simplesamlphp ERROR [f8fecb1662] 11 [builtin] (trigger_error)
Mar 18 23:55:21 simplesamlphp ERROR [f8fecb1662] 10 /var/simplesamlphp/vendor/lcobucci/jwt/src/Builder.php:169 (Lcobucci\JWT\Builder::convertToDate)
Mar 18 23:55:21 simplesamlphp ERROR [f8fecb1662] 9 /var/simplesamlphp/vendor/lcobucci/jwt/src/Builder.php:158 (Lcobucci\JWT\Builder::expiresAt)
Mar 18 23:55:21 simplesamlphp ERROR [f8fecb1662] 8 /var/simplesamlphp/modules/oidc/lib/Server/ResponseTypes/IdTokenResponse.php:128 (SimpleSAML\Modules\OpenIDConnect\Server\ResponseTypes\IdTokenResponse::getBuilder)
Mar 18 23:55:21 simplesamlphp ERROR [f8fecb1662] 7 /var/simplesamlphp/modules/oidc/lib/Server/ResponseTypes/IdTokenResponse.php:84 (SimpleSAML\Modules\OpenIDConnect\Server\ResponseTypes\IdTokenResponse::getExtraParams)
Mar 18 23:55:21 simplesamlphp ERROR [f8fecb1662] 6 /var/simplesamlphp/vendor/league/oauth2-server/src/ResponseTypes/BearerTokenResponse.php:51 (League\OAuth2\Server\ResponseTypes\BearerTokenResponse::generateHttpResponse)
Mar 18 23:55:21 simplesamlphp ERROR [f8fecb1662] 5 /var/simplesamlphp/vendor/league/oauth2-server/src/AuthorizationServer.php:202 (League\OAuth2\Server\AuthorizationServer::respondToAccessTokenRequest)
Mar 18 23:55:21 simplesamlphp ERROR [f8fecb1662] 4 /var/simplesamlphp/modules/oidc/lib/Controller/OAuth2AccessTokenController.php:35 (SimpleSAML\Modules\OpenIDConnect\Controller\OAuth2AccessTokenController::__invoke)
Mar 18 23:55:21 simplesamlphp ERROR [f8fecb1662] 3 /var/simplesamlphp/modules/oidc/lib/Services/RoutingService.php:52 (SimpleSAML\Modules\OpenIDConnect\Services\RoutingService::call)
Mar 18 23:55:21 simplesamlphp ERROR [f8fecb1662] 2 /var/simplesamlphp/modules/oidc/www/access_token.php:18 (require)
Mar 18 23:55:21 simplesamlphp ERROR [f8fecb1662] 1 /var/simplesamlphp/lib/SimpleSAML/Module.php:254 (SimpleSAML\Module::process)
Mar 18 23:55:21 simplesamlphp ERROR [f8fecb1662] 0 /var/simplesamlphp/www/module.php:10 (N/A)
```

```
Mar 18 23:55:21 simplesamlphp ERROR [f8fecb1662] SimpleSAML\Error\Exception: Error 16384 - The use of the method "withClaim" is deprecated for registered claims. Please use dedicated method instead. at /var/simplesamlphp/vendor/lcobucci/jwt/src/Builder.php:433
Mar 18 23:55:21 simplesamlphp ERROR [f8fecb1662] Backtrace:
Mar 18 23:55:21 simplesamlphp ERROR [f8fecb1662] 10 /var/simplesamlphp/www/_include.php:48 (SimpleSAML_error_handler)
Mar 18 23:55:21 simplesamlphp ERROR [f8fecb1662] 9 [builtin] (trigger_error)
Mar 18 23:55:21 simplesamlphp ERROR [f8fecb1662] 8 /var/simplesamlphp/vendor/lcobucci/jwt/src/Builder.php:433 (Lcobucci\JWT\Builder::withClaim)
Mar 18 23:55:21 simplesamlphp ERROR [f8fecb1662] 7 /var/simplesamlphp/modules/oidc/lib/Server/ResponseTypes/IdTokenResponse.php:107 (SimpleSAML\Modules\OpenIDConnect\Server\ResponseTypes\IdTokenResponse::getExtraParams)
Mar 18 23:55:21 simplesamlphp ERROR [f8fecb1662] 6 /var/simplesamlphp/vendor/league/oauth2-server/src/ResponseTypes/BearerTokenResponse.php:51 (League\OAuth2\Server\ResponseTypes\BearerTokenResponse::generateHttpResponse)
Mar 18 23:55:21 simplesamlphp ERROR [f8fecb1662] 5 /var/simplesamlphp/vendor/league/oauth2-server/src/AuthorizationServer.php:202 (League\OAuth2\Server\AuthorizationServer::respondToAccessTokenRequest)
Mar 18 23:55:21 simplesamlphp ERROR [f8fecb1662] 4 /var/simplesamlphp/modules/oidc/lib/Controller/OAuth2AccessTokenController.php:35 (SimpleSAML\Modules\OpenIDConnect\Controller\OAuth2AccessTokenController::__invoke)
Mar 18 23:55:21 simplesamlphp ERROR [f8fecb1662] 3 /var/simplesamlphp/modules/oidc/lib/Services/RoutingService.php:52 (SimpleSAML\Modules\OpenIDConnect\Services\RoutingService::call)
Mar 18 23:55:21 simplesamlphp ERROR [f8fecb1662] 2 /var/simplesamlphp/modules/oidc/www/access_token.php:18 (require)
Mar 18 23:55:21 simplesamlphp ERROR [f8fecb1662] 1 /var/simplesamlphp/lib/SimpleSAML/Module.php:254 (SimpleSAML\Module::process)
Mar 18 23:55:21 simplesamlphp ERROR [f8fecb1662] 0 /var/simplesamlphp/www/module.php:10 (N/A)
```

2021-04-21 15:03 UTC, pradtke commented
@mdusher Thanks for the PR. We're still figuring out the review and merge process for this module. We'll try to get this merged in soon.

2021-04-21 15:36 UTC, pradtke requested changes

2021-04-21 15:36 UTC, pradtke commented on lib/Server/ResponseTypes/IdTokenResponse.php
> +                case RegisteredClaims::AUDIENCE:
`RegisteredClaim`  is missing an import/use  (.e.g `use Lcobucci\JWT\Token\RegisteredClaims;`)

2021-04-21 15:36 UTC, pradtke commented on lib/Server/ResponseTypes/IdTokenResponse.php
> +                    $builder->issuedAt(new DateTimeImmutable($claimValue));
`DateTimeImmutable` needs an imprt/use (`use DateTimeImmutable;`)  or to be qualified (`\DateTimeImmutable`)

2021-04-21 15:36 UTC, pradtke commented on lib/Server/ResponseTypes/IdTokenResponse.php
> +                    $builder->issuedAt(new DateTimeImmutable($claimValue));
I believe  $claimValue is a unix timestamp. To pass it into `DateTimeImmutable` I believe it needs to be the string `'@' . $claimValue`.  See "Unix Timestamp" under https://www.php.net/manual/en/datetime.formats.compound.php

2021-04-21 15:36 UTC, pradtke commented on lib/Server/ResponseTypes/IdTokenResponse.php
> +                    $builder->expiresAt($claimValue);
This will need to use DateTimeImmutable as well.

2021-04-21 15:36 UTC, pradtke commented on lib/Server/ResponseTypes/IdTokenResponse.php
> +                    $builder->canOnlyBeUsedAfter($claimValue);
This will also need to use `DateTimeImmutable`

2021-04-21 22:50 UTC, mdusher commented
@pradtke thanks for the feedback! I've updated the commit with the changes - but I'm currently unable to test it as I don't have an environment that uses it at the moment.

2021-05-03 14:48 UTC, pradtke approved these changes

2021-05-04 15:25 UTC, merged

2021-05-04 15:26 UTC, pradtke commented
@mdusher Thank you for these fixes.